# fly.toml app configuration file generated for bethtest on 2023-07-16T04:53:13-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "panda-css-htmx"
primary_region = "ord"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]